baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Blog LabVeilTech'
theme = 'PaperMod'

[params]
    [params.homeInfoParams]
        title = 'LabVeilTech'
        content = 'Bienvenue sur mon blog'

    [params.cover]
        linkFullPage = false

[menu]
  [[menu.main]]
    name = 'Blog'
    url = '/posts/'
    weight = 1
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 2
